# Generated by Django 4.2.17 on 2025-01-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_remove_userprofile_points_achievement_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=7,
            ),
        ),
    ]
