# Generated by Django 4.2.17 on 2025-01-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0003_workout_visibility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="description",
            new_name="steps",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="category",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="visibility",
        ),
        migrations.AddField(
            model_name="workout",
            name="difficulty",
            field=models.CharField(default="easy", max_length=10),
        ),
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="workout",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
