# Generated by Django 4.2.17 on 2025-01-03 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_rename_description_workout_steps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workout",
            name="difficulty",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="workout",
            name="duration",
            field=models.FloatField(),
        ),
    ]
