# Generated by Django 4.2.17 on 2025-01-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_workout_created_at_alter_workout_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
