# Generated by Django 4.2.17 on 2025-01-03 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0006_workout_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userworkout",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="userworkout",
            name="date_completed",
        ),
        migrations.AddField(
            model_name="userworkout",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userworkout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userworkout",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="training.workout"
            ),
        ),
    ]
