# Generated by Django 4.2.17 on 2025-01-03 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0007_remove_userworkout_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="created_at",
        ),
        migrations.AddField(
            model_name="userworkout",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workout",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="workout",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
