# Generated by Django 4.2.17 on 2025-01-03 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0008_remove_workout_created_at_userworkout_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
