# Generated by Django 4.2.17 on 2025-01-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0009_workout_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchallenge",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="userchallenge",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userworkout",
            name="deleted",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="UserChallenge",
        ),
    ]
